### ISSUE TITLE
Documenting auth / user management

### ISSUE THREAD

**Issue by lucagobbi** [cheshire-cat-ai/docs#178]
This is a big one.

Since 1.7.0, Cheshire Cat Core has introduced authentication handlers, user management, and related features.

I propose that we track the necessary tasks here. I'd like to work on this, but I stopped myself from starting immediately writing because I believe we need to plan first due to the extensive changes required. We should also decide on a clear and easy-to-understand structure.

Plus, the old documentation needs updating. e.g. Some users are copying examples from WebSocket that no longer work. We need to clarify that with authentication enabled, certain adjustments need to be done.

What do you think?

**Comment by pieroit** [comment]
> This is a big one.
> 
> Since 1.7.0, Cheshire Cat Core has introduced authentication handlers, user management, and related features.
> 
> I propose that we track the necessary tasks here. I'd like to work on this, but I stopped myself from starting immediately writing because I believe we need to plan first due to the extensive changes required. We should also decide on a clear and easy-to-understand structure.
> 

CCAT_API_KEY, CCAT_API_KEY_WS and JWT can be documented, I suggest we do not document auth handlers yet because the api may change (no use cases observed)
Not sure about permissions

> Plus, the old documentation needs updating. e.g. Some users are copying examples from WebSocket that no longer work. We need to clarify that with authentication enabled, certain adjustments need to be done.
> 

> What do you think?

Agree, I guess most people want to know:
1 - how do I use endpoints (http and ws)
2 - how do I secure the installation
3 - how do I use the endpoints after securing the installation

The tests are full of examples to be copy pasted

Thanks for starting this @lucagobbi
