### ISSUE TITLE
Mention plugin template and registry in the docs

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/docs#25]
As a first guide on how to create a plugin, the easiest way is to let cat learners create a folder in `cat/plugins` and hack locally without clouding their minds about plugin versioning and publishing.
We already do this in the docs in the `techcnical/plugins` section but we totally omit that there is a ready-to-go template and the possibility to submit plugins to the registry.
I suggest we add a page `publish your plugin` to guide on these topics

**Comment by EugenioPetulla** [comment]
@pieroit I almost finished to write this documentation. The last piece of the puzzle is a chapter to explain how to get in touch and keep updated on registry changes. What do you propose? I remand this to the Discord channel? We want to institute a mailing list or something like that?

It's something we have to solve because not all the developers can be on Discord I think :(

**Comment by pieroit** [comment]
> @pieroit I almost finished to write this documentation. 

Great 😃

> The last piece of the puzzle is a chapter to explain how to get in touch and keep updated on registry changes. What do you propose? I remand this to the Discord channel? We want to institute a mailing list or something like that?

Let's start with the discord!

> It's something we have to solve because not all the developers can be on Discord I think :(

You are right, we'll think about this at due time - it's gonna be due time when external devs will ask for a way to keep in touch

Thanks 🙏
